### ISSUE TITLE
issue in taking attendance

### ISSUE THREAD

**Issue by teflx** [shubhamkumar27/Face_recognition_based_attendance_system#2]
while taking attendance it giving the error the is no face attribute in cv2 module
![Screenshot_20220425_103843](https://user-images.githubusercontent.com/104340710/165024497-8f187047-c2b8-448b-8c58-a32c70f37d88.png)
there is screen shot of error please help me out

**Comment by AbdrrahimDahmani** [comment]
i found this problem too

**Comment by AbdrrahimDahmani** [comment]
try to install opencv-python and opencv-contrib-python packages then it will work with you

**Comment by teflx** [comment]
> try to install opencv-python and opencv-contrib-python packages then it will work with you

thank it work in my case
